apiVersion: apps/v1
kind: Deployment
metadata:
  name: titiler
  labels:
    k8s-app: titiler
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: titiler
  template:
    metadata:
      labels:
        k8s-app: titiler
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: titiler
        image: ghcr.io/developmentseed/titiler:0.24.2
        imagePullPolicy: Always
        command: ["uvicorn"]
        args: [
          "titiler.application.main:app",
          "--host", "0.0.0.0",
          "--port", "8000",
          "--workers", "4"
        ]
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        resources:
          requests:
            cpu: 6
            memory: 24Gi
          limits:
            cpu: 12
            memory: 40Gi
        env:
        - name: CPL_TMPDIR
          value: "/tmp"
        - name: GDAL_CACHEMAX
          value: "2000" # 2000 mb
        - name: VSI_CACHE
          value: "TRUE"
        - name: VSI_CACHE_SIZE
          value: "50000000" # 50 MB (per file-handle)
        - name: GDAL_DISABLE_READDIR_ON_OPEN
          value: "EMPTY_DIR"
        - name: GDAL_HTTP_MERGE_CONSECUTIVE_RANGES
          value: "YES"
        - name: PYTHONWARNINGS
          value: "ignore"
        - name: WEB_CONCURRENCY
          value: "4"
        - name: GDAL_HTTP_MAX_RETRY
          value: "3"
        - name: GDAL_HTTP_RETRY_DELAY
          value: "1"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

