apiVersion: apps/v1
kind: Deployment
metadata:
  name: titiler
  labels:
    k8s-app: titiler
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: titiler
  template:
    metadata:
      labels:
        k8s-app: titiler
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: titiler
        image: ghcr.io/developmentseed/titiler:0.24.2
        imagePullPolicy: Always
        command: ["uvicorn"]
        args: [
          "titiler.application.main:app",
          "--host", "0.0.0.0",
          "--port", "8000",
          "--workers", "1"
        ]
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        resources:
          requests:
            cpu: 8
            memory: 32Gi
          limits:
            cpu: 8
            memory: 32Gi
        env:
        - name: CPL_TMPDIR
          value: "/tmp"
        - name: GDAL_CACHEMAX
          value: "200" # 200 mb
        - name: VSI_CACHE
          value: "TRUE"
        - name: VSI_CACHE_SIZE
          value: "5000000" # 5 MB (per file-handle)
        - name: GDAL_DISABLE_READDIR_ON_OPEN
          value: "EMPTY_DIR"
        - name: GDAL_HTTP_MERGE_CONSECUTIVE_RANGES
          value: "YES"
        - name: PYTHONWARNINGS
          value: "ignore"
        - name: WEB_CONCURRENCY
          value: "2"
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 6
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3

