apiVersion: apps/v1
kind: Deployment
metadata:
  name: titiler
  labels:
    k8s-app: titiler
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: titiler
  template:
    metadata:
      labels:
        k8s-app: titiler
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - name: titiler
        image: ghcr.io/developmentseed/titiler:0.24.2
        imagePullPolicy: Always
        command: ["uvicorn"]
        args: [
          "titiler.application.main:app",
          "--host", "0.0.0.0",
          "--port", "8000",
          "--workers", "1"
        ]
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        resources:
          requests:
            cpu: 8
            memory: 32Gi
          limits:
            cpu: 8
            memory: 32Gi
        env:
          CPL_TMPDIR: /tmp
          GDAL_CACHEMAX: 200 # 200 mb
          VSI_CACHE: TRUE
          VSI_CACHE_SIZE: 5000000 # 5 MB (per file-handle)
          GDAL_DISABLE_READDIR_ON_OPEN: EMPTY_DIR
          GDAL_HTTP_MERGE_CONSECUTIVE_RANGES: YES
          PYTHONWARNINGS: ignore
          WEB_CONCURRENCY: 2

