apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    haproxy.org/timeout-server: "300s"
    haproxy.org/timeout-client: "300s"
    haproxy.org/timeout-connect: "30s"
    haproxy.org/timeout-http-request: "300s"
  name: titiler
spec:
  ingressClassName: haproxy
  rules:
  - host: titiler.nrp-nautilus.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: titiler
            port:
              number: 8000
  tls:
  - hosts:
    - titiler.nrp-nautilus.io
