apiVersion: v1
kind: Service
metadata:
  name: titiler
  labels:
    k8s-app: titiler

# ports.targetPort is the port exposed by the Docker container
# ports.port is the port matched to the ingress
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    k8s-app: titiler
  type: ClusterIP
